### ISSUE TITLE
clarify what type of output from ausplotsr is supposed to go into calculate_field_diversity

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/saltbush#6]
there are a lot of confusing options for `ausplotsR::get_ausplots`

but i think only one type is designed to go into `calculate_field_diversity`?

**Comment by wcornwell** [comment]
current approach:
```
my.data <- get_ausplots(my.Plot_IDs=c("SATFLB0004", "QDAMGD0022", "NTASTU0002"),veg.PI=TRUE,site_info=TRUE)
 twentyfour_diversity <- calculate_field_diversity(my.data$veg.PI)
 twentyfour_diversity
```

**Comment by wcornwell** [comment]
not working:
<img width="1182" alt="Screenshot 2024-11-18 at 3 00 29 pm" src="https://github.com/user-attachments/assets/1d5e01e5-447f-4e0c-8eb5-78d24b132251">

**Comment by adelegem** [comment]
should be 
my.data <- get_ausplots(my.Plot_IDs=c("SATFLB0004", "QDAMGD0022", "NTASTU0002"),veg.PI=TRUE)$veg.PI
have fixed some things in the code + added a working example
